name: Release
on:
  pull_request:
    branches: main
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    # releaseブランチからmainにPRがマージされたら
    if: |
      github.event.pull_request.merged == true
      && startsWith(github.head_ref, 'release/v')
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          always-auth: true
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Publish
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
